export const ADAPTIVE_REVIEW_CONFIG = Object.freeze({
  defaultSessionSize: 20,
  minimumSessionSize: 1,
  maximumSessionSize: 50,
  currentChapterWindow: 1,
  recentEventWindowDays: 30,
  maintenanceAfterDays: 14,
  maximumSupportVocabulary: 40,
  distributions: {
    NORMAL: {
      DUE: 0.4,
      BACKLOG: 0.3,
      CURRENT: 0.2,
      MAINTENANCE: 0.1,
    },
    BACKLOG_SCREENING: {
      DUE: 0.2,
      BACKLOG: 0.8,
      CURRENT: 0,
      MAINTENANCE: 0,
    },
  },
  priority: {
    bucketBase: { DUE: 45, BACKLOG: 18, CURRENT: 22, MAINTENANCE: 4 },
    stageNeed: {
      NEW: 28,
      RECOGNITION: 24,
      CONTEXT_RECOGNITION: 19,
      GUIDED_RECALL: 14,
      PRODUCTION: 8,
      MASTERED: 0,
    },
    overduePerDay: 4,
    maximumOverdueBonus: 80,
    recognitionDeficit: 0.1,
    productionDeficit: 0.24,
    morphologyDeficit: 0.08,
    productionGap: 0.28,
    lapse: 8,
    recentIncorrect: 11,
    recentCorrect: -2,
    streak: -1.5,
    maximumStreakDiscount: -12,
    neverReviewed: 22,
    daysSinceReview: 0.75,
    maximumTimeBonus: 35,
    currentChapter: 18,
    previousChapter: 11,
    nearbyChapter: 5,
    frequency: 2,
    displacementMargin: 25,
    maximumDisplacementRatio: 0.15,
    varietyPriorityTolerance: 18,
  },
  stageThresholds: {
    recognition: { score: 20, successes: 1 },
    contextRecognition: { score: 45, successes: 3 },
    guidedRecall: { recognitionScore: 65, recallSuccesses: 2 },
    production: { score: 55, recallSuccesses: 4, productionSuccesses: 1 },
    mastered: {
      recognitionScore: 85,
      productionScore: 80,
      morphologyScore: 60,
      recallSuccesses: 8,
      productionSuccesses: 4,
      streak: 4,
      minimumLearningDays: 7,
    },
    errorsBeforeDemotion: 3,
  },
  scheduling: {
    scoreDeltas: { CORRECT: 12, PARTIAL: 4, INCORRECT: -7 },
    minimumIntervalByStage: {
      NEW: 1,
      RECOGNITION: 1,
      CONTEXT_RECOGNITION: 3,
      GUIDED_RECALL: 7,
      PRODUCTION: 14,
      MASTERED: 30,
    },
    correctEaseDelta: 0.05,
    partialEaseDelta: -0.05,
    incorrectEaseDelta: -0.2,
    minimumEase: 1.3,
    maximumEase: 3,
    partialIntervalMultiplier: 0.75,
    incorrectIntervalMultiplier: 0.5,
  },
  exerciseEvidence: {
    resultBase: { CORRECT: 6, PARTIAL: 2.5, INCORRECT: -5 },
    types: {
      VOCABULARY_MULTIPLE_CHOICE: { recognition: 1 },
      CONTEXT_MEANING: { recognition: 1.2 },
      TRANSLATION_LA_ES: { recognition: 1.3 },
      TRANSLATION_ES_LA: { production: 2, morphology: 0.35 },
      INFLECTION_COMPLETION: { morphology: 1.7, production: 0.35 },
      INFLECTION_MULTIPLE_CHOICE: { morphology: 1.3 },
      GUIDED_RECALL: { production: 1.6, morphology: 0.35 },
      LEMMA_IDENTIFICATION: { recognition: 1, morphology: 0.8 },
      MORPHOLOGY_PRODUCTION: { morphology: 2, production: 0.25 },
      FREE_PRODUCTION: { production: 2.3, morphology: 0.7 },
    },
    errorPenalty: {
      MACRON_ONLY: 0,
      SPELLING: 0.45,
      WORD_ORDER: 0.35,
      INCOMPLETE_RESPONSE: 0.55,
      WRONG_MEANING: 1,
      WRONG_CASE: 1,
      WRONG_NUMBER: 0.9,
      WRONG_GENDER: 0.8,
      WRONG_PERSON: 0.9,
      WRONG_TENSE: 1,
      WRONG_VOICE: 0.9,
      WRONG_LEMMA: 1,
    },
  },
})

export const ADAPTIVE_EXERCISE_TYPES = Object.freeze([
  'VOCABULARY_MULTIPLE_CHOICE',
  'CONTEXT_MEANING',
  'TRANSLATION_LA_ES',
  'TRANSLATION_ES_LA',
  'INFLECTION_COMPLETION',
  'INFLECTION_MULTIPLE_CHOICE',
  'GUIDED_RECALL',
  'LEMMA_IDENTIFICATION',
  'MORPHOLOGY_PRODUCTION',
  'FREE_PRODUCTION',
])

export const SOURCE_BUCKETS = Object.freeze([
  'DUE',
  'BACKLOG',
  'CURRENT',
  'MAINTENANCE',
])
